# Site settings
title: Lens
description: Just another fine responsive site template by <a href="http://html5up.net">HTML5 UP</a>
baseurl: "/beautifulphotos" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: "JuHyung Son"

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url: http://jusonn.github.io
gitlab_url:
googleplus_url:
instagram_url: http://instagram.com/juworld
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
